/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.paypay.baymax.commons.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.paypay.baymax.commons.type.OperComboListAllType;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-18T23:13:42.544-05:00[America/Mexico_City]")
@Api(value = "combo", description = "the combo API")
public interface ComboApi {

    @ApiOperation(value = "Gets a combo by an option", nickname = "getCombo", notes = "Get a list of combo by an option depending of the parameter ", response = OperComboListAllType.class, tags={ "Combo", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = OperComboListAllType.class) })
    @RequestMapping(value = "/combo/{option}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<OperComboListAllType> getCombo(@ApiParam(value = "Combo",required=true) @PathVariable("option") String option);

    @ApiOperation(value = "Gets a combo by parameter", nickname = "getComboByParameter", notes = "Get a list of combo by an extra parameter ", response = OperComboListAllType.class, tags={ "Combo", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = OperComboListAllType.class) })
    @RequestMapping(value = "/combo/{option}/parameter/{parameter}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<OperComboListAllType> getComboByParameter(@ApiParam(value = "Combo",required=true) @PathVariable("option") String option,@ApiParam(value = "Combo",required=true) @PathVariable("parameter") String parameter);

}
