/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.paypay.baymax.commons.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.paypay.baymax.commons.type.OperReviewAllType;
import com.paypay.baymax.commons.type.OperReviewListAllType;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-09-13T17:05:15.456-05:00[America/Mexico_City]")
@Api(value = "review", description = "the review API")
public interface ReviewApi {

    @ApiOperation(value = "Delete a record.", nickname = "disable", notes = "Delete (Logically) one or multiple records of a review ", tags={ "Performance", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation") })
    @RequestMapping(value = "/review/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> disable(@ApiParam(value = "Review ID",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "Get all records.", nickname = "getAll", notes = "Get all the records of the reviews ", response = OperReviewListAllType.class, tags={ "Performance", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = OperReviewListAllType.class) })
    @RequestMapping(value = "/review",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<OperReviewListAllType> getAll();


    @ApiOperation(value = "Gets a review by ID.", nickname = "getReviewById", notes = "Get all the reviews by an ID as an object ", response = OperReviewAllType.class, tags={ "Performance", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = OperReviewAllType.class) })
    @RequestMapping(value = "/review/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<OperReviewAllType> getReviewById(@ApiParam(value = "Review ID",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "Insert a new Object.", nickname = "save", notes = "Insert one single record of a review ", response = OperReviewAllType.class, tags={ "Performance", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = OperReviewAllType.class) })
    @RequestMapping(value = "/review",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<OperReviewAllType> save(@ApiParam(value = "Insert a review object." ,required=true )  @Valid @RequestBody OperReviewAllType body);


    @ApiOperation(value = "Update a record.", nickname = "update", notes = "Update one single record of a review ", response = OperReviewAllType.class, tags={ "Performance", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = OperReviewAllType.class) })
    @RequestMapping(value = "/review",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<OperReviewAllType> update(@ApiParam(value = "Update a review object." ,required=true )  @Valid @RequestBody OperReviewAllType body);

}
